services:
  - docker

jobs:
  include:
    - stage: "Test Consumer"
      name: "Unit"
      script: |
        make test_unit_ci

    - name: "Contract"
      script: |
        make test_contract_ci

    - stage: "Publish contract of Consumer"
      script: |
        make publish_pact_ci

    - stage: "Deploy"
      name: "Deploy to prod"
      env:
        - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
      script: |
        printenv
        make deploy_to_prod
      if: branch =~ /^(master_v1|fake_deploy).*/
